# general settings
name: LIVEC

model_type: GeneralIQAModel
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# experiments_save_dir: ./experiments/LIVEC

# dataset and data loader settings
datasets:
  train:
    name: LIVEC
    type: LIVEChallengeDataset
    dataroot_target: /your_data_path/ChallengeDB_release/Images
    meta_info_file: ./datasets/meta_info/meta_info_LIVEChallengeDataset.csv
    split_file: ./datasets/meta_info/livec_10split.pkl
    mos_range: [0, 100]
    lower_better: false 
    mos_normalize: true
    split_index: 1 # default 1, set 1-10 for other split

    augment:
      hflip: true
      random_crop: 224
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: LIVEC
    type: LIVEChallengeDataset
    dataroot_target: /your_data_path/ChallengeDB_release/Images
    meta_info_file: ./datasets/meta_info/meta_info_LIVEChallengeDataset.csv
    split_file: ./datasets/meta_info/livec_10split.pkl
    mos_range: [0, 100]
    lower_better: false
    mos_normalize: true
    split_index: 1

    num_worker_per_gpu: 4
    batch_size_per_gpu: 1

# network structures
network:
  type: UniQA_Adapter_Patchtest
  model_type: CLIP_Adapter_prompt
  backbone: /path/xxxx/UniQA_weight.pt
  pretrained: false
  pos_embedding: true
  sample_size: 224
  # clip_finetune: false
  clip_finetune: true # use UniQA weights, clip_finetune should be true
  # embedding_dim: 512

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: Adam 
    lr: !!float 2e-4
  
  scheduler:
    type: CosineAnnealingLR
    T_max: 50
    eta_min: 0

  total_iter: 2000000
  total_epoch: 50
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: MSELoss
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 200
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately 
  metrics:
    srcc: 
      type: calculate_srcc

    plcc: 
      type: calculate_plcc

# logging settings
logger:
  print_freq: 100
  save_latest_freq: !!float 1e3 
  log_imgs_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: True
