csiq:
  name: CSIQ
  type: GeneralFRDataset
  dataroot_target: ./datasets/CSIQ/dst_imgs
  dataroot_ref: ./datasets/CSIQ/src_imgs
  meta_info_file: ./datasets/meta_info/meta_info_CSIQDataset.csv
  mos_range: [0, 1]
  lower_better: true

tid2008:
  name: TID2008
  type: GeneralFRDataset
  dataroot_target: ./datasets/tid2008/distorted_images
  dataroot_ref: ./datasets/tid2008/reference_images
  meta_info_file: ./datasets/meta_info/meta_info_TID2008Dataset.csv
  mos_range: [0, 9]
  lower_better: false 

tid2013:
  name: TID2013
  type: GeneralFRDataset
  dataroot_target: ./datasets/tid2013/distorted_images
  dataroot_ref: ./datasets/tid2013/reference_images
  meta_info_file: ./datasets/meta_info/meta_info_TID2013Dataset.csv
  mos_range: [0, 9]
  lower_better: false 

live:
  name: LIVE
  type: GeneralFRDataset
  dataroot_target: './datasets/LIVEIQA_release2'
  meta_info_file: './datasets/meta_info/meta_info_LIVEIQADataset.csv'
  mos_range: [1, 100]
  lower_better: true

livem:
  name: LIVEM
  type: GeneralFRDataset
  dataroot_target: './datasets/LIVEmultidistortiondatabase'
  meta_info_file: './datasets/meta_info/meta_info_LIVEMDDataset.csv'
  mos_range: [1, 100]
  lower_better: true

livec:
  name: LIVEC
  type: LIVEChallengeDataset
  dataroot_target: ./datasets/LIVEC/
  meta_info_file: ./datasets/meta_info/meta_info_LIVEChallengeDataset.csv
  mos_range: [1, 100]
  lower_better: false 

koniq10k:
  name: KonIQ10k
  type: GeneralNRDataset
  dataroot_target: './datasets/koniq10k/512x384'
  meta_info_file: './datasets/meta_info/meta_info_KonIQ10kDataset.csv'
  split_index: 'official_split'
  phase: 'test'
  mos_range: [1, 100]
  lower_better: false 

koniq10k-1024:
  name: KonIQ10k
  type: GeneralNRDataset
  dataroot_target: './datasets/koniq10k/1024x768'
  meta_info_file: './datasets/meta_info/meta_info_KonIQ10kDataset.csv'
  split_index: 'official_split'
  phase: 'test'
  mos_range: [0, 100]
  lower_better: false 

koniq10k++:
  name: KonIQ10k++
  type: GeneralNRDataset
  dataroot_target: './datasets/koniq10k/512x384'
  meta_info_file: './datasets/meta_info/meta_info_KonIQ10k++Dataset.csv'
  split_index: 'official_split'
  phase: 'test'
  mos_range: [1, 5]
  lower_better: false

kadid10k:
  name: KADID10k
  type: GeneralFRDataset
  dataroot_target: './datasets/kadid10k/images'
  meta_info_file: './datasets/meta_info/meta_info_KADID10kDataset.csv'
  mos_range: [1, 5]
  lower_better: false

spaq:
  name: SPAQ
  type: GeneralNRDataset
  dataroot_target: './datasets/SPAQ/TestImage'
  meta_info_file: './datasets/meta_info/meta_info_SPAQDataset.csv'
  augment:
    resize: 448
  mos_range: [1, 100]
  lower_better: false

ava:
  name: AVA
  type: AVADataset
  dataroot_target: './datasets/AVA_dataset/ava_images/'
  meta_info_file: './datasets/meta_info/meta_info_AVADataset.csv'
  split_index: 'official_split'
  mos_range: [1, 10]
  lower_better: false

pipal:
  name: PIPAL
  type: GeneralFRDataset 
  dataroot_target: './datasets/PIPAL/Dist_Imgs'
  dataroot_ref: './datasets/PIPAL/Train_Ref'
  meta_info_file: './datasets/meta_info/meta_info_PIPALDataset.csv'
  split_index: 'official_split'
  mos_range: [0, 1]
  lower_better: false 

flive:
  name: FLIVE
  type: GeneralNRDataset 
  dataroot_target: './datasets/FLIVE_Database/database'
  meta_info_file: './datasets/meta_info/meta_info_FLIVEDataset.csv'
  split_index: 'official_split'
  phase: test
  mos_range: [0, 100]
  lower_better: false

pieapp:
  name: PieAPPDataset
  type: PieAPPDataset 
  dataroot_target: './datasets/PieAPP_dataset_CVPR_2018/'
  meta_info_file: './datasets/meta_info/meta_info_PieAPPDataset.csv'
  split_index: 'official_split'

bapps:
  name: BAPPS
  type: BAPPSDataset
  dataroot_target: './datasets/PerceptualSimilarity/dataset'
  meta_info_file: './datasets/meta_info/meta_info_BAPPSDataset.csv'

# piq:
#   name: PIQ2023
#   type: PIQDataset 
#   dataroot_target: ./datasets/PIQ
#   meta_info_file: ./datasets/meta_info/meta_info_PIQDataset.csv
#   split_index: 1 

gfiqa:
  name: GFIQA 
  type: GeneralNRDataset
  dataroot_target: ./datasets/GFIQA/image
  meta_info_file: ./datasets/meta_info/meta_info_GFIQADataset.csv
  split_index: 1

cgfiqa:
  name: CGFIQA
  type: GeneralNRDataset
  dataroot_target: ./datasets/CGFIQA/
  meta_info_file: ./datasets/meta_info/meta_info_CGFIQADataset.csv
  split_index: 'official_split'